"""create_llm_usage_table

Revision ID: b9bc5c49615e
Revises: 1b2bea35ef5f
Create Date: 2026-10-01 10:48:01.211722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bc5c49615e'
down_revision: Union[str, Sequence[str], None] = '1b2bea35ef5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_agent_id'), 'llm_usage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_created_at'), 'llm_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_model'), 'llm_usage', ['model'], unique=False)
    op.create_index('ix_llm_usage_model_created', 'llm_usage', ['model', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_request_id'), 'llm_usage', ['request_id'], unique=False)
    op.create_index('ix_llm_usage_user_created', 'llm_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_user_id'), 'llm_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_user_id'), table_name='llm_usage')
    op.drop_index('ix_llm_usage_user_created', table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_request_id'), table_name='llm_usage')
    op.drop_index('ix_llm_usage_model_created', table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_model'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_created_at'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_agent_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
